railmapgen/rmg

.idea/.gitignore
.idea/RailMapGenerator.iml
.idea/inspectionProfiles/Project_Default.xml
.idea/jsLibraryMappings.xml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
docs/environment-set-up.md
index.html
styles/main.css
webpack.config.js

Added a choser

---

src/svgs/railmap/main/station/station-shmetro.tsx

update(shmetro): decro line for int station #29.2

---

src/svgs/railmap/main/station/station-shmetro.tsx

fix #29.2
[mentioned here](http://www.ditiezu.com/forum.php?mod=redirect&goto=findpost&ptid=659763&pid=11480801&fromuid=736386)

fix(shmetro): simplify stn decro line

---

public/locale/en.json
public/locale/zh-HK.json
public/locale/zh-Hans.json
src/constants/constants.ts
src/constants/templates/shmetro/sh11.ts
src/redux/param/reducer.ts
src/svgs/indoor/indoor-shmetro.tsx
src/svgs/indoor/station-shmetro.tsx
src/svgs/railmap/main/main-shmetro.tsx
src/svgs/railmap/main/station/station-shmetro.tsx
src/svgs/railmap/methods/share.ts
src/svgs/svg.tsx
src/utils.ts

* #82 Indoor canvas of Shanghai Metro
* fix for redux update
* support split station name in indoor
* add missing style
* branches in indoor
* comment out unused code
* fix typo
* fix build warning
* remove unused export

#82 Add indoor canvas for Shanghai metro

---

src/svgs/destination/destination-shmetro.tsx
src/svgs/indoor/indoor-shmetro.tsx

#137 Incomplete render of text station in destination panel of Shanghai Metro

---

package-lock.json
package.json
src/components/side-panel/coline-side-panel/info-section.tsx
src/redux/param/coline-actions.test.ts
src/redux/param/remove-station-action.test.ts
src/setupTests.tsx
src/svgs/railmap/methods/shmetro-coline.ts

Test on underlying validity algorithm. No actions or SVG-specific parts are involved.

#251 coline unit tests

---

src/components/common/rmg-fields.tsx
src/components/side-panel/station-side-panel/more-section.tsx
src/components/side-panel/style-side-panel/loop-section.tsx
src/components/side-panel/style-side-panel/style-side-panel.tsx
src/constants/constants.ts
src/constants/templates/shmetro/sh4.ts
src/redux/param/action.ts
src/redux/param/add-station-action.ts
src/redux/param/reducer.ts
src/svgs/railmap/main/loop-shmetro.tsx
src/utils.ts

#269 Loopline UI and Redux

---

src/svgs/destination/destination-shmetro.tsx

#271 Loopline destination

---

package-lock.json
package.json
src/components/page-header/page-header.tsx
src/components/root/window-header.tsx
src/i18n/translations/zh-Hans.json
src/i18n/translations/zh-Hant.json
src/index.tsx
src/redux/app/action.test.ts
src/redux/app/action.ts
src/redux/app/reducer.ts

#323 Use Slider to implement zoom in/out functionality

---

.github/workflows/build2.yml
scripts/build.sh

#511 Bump version after build

---

src/util/export-utils.ts

Use the standard API in MDN.
https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration

#521 Fix downloading mtr images in Firefox

---

src/components/param-selector-view/app-clip-view.tsx

#544 Update param schema version before exporting via app clip view

---

public/styles/share_mtr.css
src/svgs/mtr/destination-mtr.tsx
src/svgs/mtr/platform-number.tsx
src/svgs/mtr/railmap-mtr.tsx
src/svgs/mtr/station/interchange-tick.tsx
src/svgs/mtr/station/osi-station.tsx
src/svgs/mtr/station/station-name/station-name-wrapper.tsx
src/svgs/mtr/station/station-name/station-name.tsx
src/svgs/mtr/strip-mtr.tsx
src/util/export-utils.ts

#546 Resize elements of MTR styles

---

src/svgs/gzmtr/station-name/station-secondary-name.tsx

#560 Do not display brackets when secondary name is empty

---

src/components/app-clip/rmg-templates-app-clip.tsx
src/components/param-selector-view/app-clip-view.tsx
src/components/param-selector-view/index.tsx
src/components/param-selector-view/selector-actions.tsx
src/components/root/app-view.tsx
src/constants/constants.ts
src/redux/app/action.test.ts
src/redux/app/action.ts
src/redux/init.test.ts
src/redux/init.ts
src/setupTests.ts
src/util/param-manager-utils.test.ts
src/util/param-manager-utils.ts

#584 Remove legacy localStorage keys support

---

.github/workflows/build2.yml
.github/workflows/code-check.yml
src/components/side-panel/station-side-panel/branch-section.tsx
src/components/side-panel/station-side-panel/more-section.tsx
src/components/side-panel/style-side-panel/gzmtr-note-section.tsx
src/constants/constants.ts
src/redux/helper/graph-theory-util.test.ts
src/redux/helper/graph-theory-util.ts
src/redux/param/action.test.ts
src/redux/param/action.ts
src/redux/param/add-station-action.ts
src/redux/param/connect-disconnect-branch.ts
src/redux/param/remove-station-action.test.ts
src/redux/param/remove-station-action.ts
src/redux/param/util.ts
src/setupTests.ts
src/svgs/gzmtr/railmap-gzmtr.tsx
src/svgs/gzmtr/station.tsx
src/svgs/mtr/station/station-name/station-name-wrapper.tsx
src/svgs/shmetro/station-shmetro.tsx
src/util/param-updater-utils.test.ts
src/util/param-updater-utils.ts

#586 Sanitise empty fields when using param

---

src/svgs/shmetro/indoor/indoor-shmetro.tsx
src/svgs/shmetro/indoor/station-shmetro.tsx

#620 Shanghai Metro new Out-of-station Interchange

---

src/components/app-clip/rmg-templates-app-clip.tsx

#630 Disable templates app clip on Gitee

---

src/setupTests.ts
src/svgs/mtr/destination-mtr.test.tsx
src/svgs/mtr/destination-mtr.tsx

#643 Only platform number is shown in MTR terminal station

---

src/svgs/mtr/destination-mtr.tsx

#657 Fix MTR platform number position

---

src/components/side-panel/station-side-panel/info-section.tsx
src/i18n/translations/zh-Hans.json
src/i18n/translations/zh-Hant.json

#660 Support disabling secondary names for GZMTR stations

---

src/components/side-panel/station-side-panel/more-section.tsx
src/constants/constants.ts
src/i18n/translations/en.json
src/i18n/translations/zh-Hans.json
src/i18n/translations/zh-Hant.json
src/redux/param/action.ts
src/redux/param/util.ts
src/svgs/config.ts
src/svgs/shanghaisuburbanrailway/destination-shsubrwy.tsx
src/svgs/shanghaisuburbanrailway/index.tsx
src/svgs/shanghaisuburbanrailway/platform-shsubrwy.tsx
src/svgs/shanghaisuburbanrailway/runin-shsubrwy.tsx
src/svgs/shmetro/destination-shmetro.tsx
src/util/param-updater-utils.test.ts
src/util/param-updater-utils.ts

This should be built with a minor update to v5.18

#674 Shanghai Suburban Railway style

---

src/svgs/mtr/station/interchange-tick.tsx
src/svgs/mtr/station/station-name/station-name-wrapper.tsx

#691 #692 Fix alignment issue of MTR interchange station with facility icons

---

public/styles/share_gzmtr.css
src/svgs/gzmtr/runin/runin-gzmtr.tsx
src/svgs/gzmtr/runin/runin-utils.ts
src/svgs/gzmtr/strip-gzmtr.tsx

#696 Enlarge elements on GZMTR runin

---

src/svgs/gzmtr/current-station-name.tsx
src/svgs/gzmtr/info-gzmtr.tsx

#697 Fix GZMTR runin station name spacing

---

package-lock.json
package.json
public/styles/share_gzmtr.css
src/svgs/gzmtr/station.tsx

#738 Adapt latest svg-assets

---

package-lock.json
package.json
src/svgs/gzmtr/info-gzmtr.tsx
src/svgs/gzmtr/main-gzmtr.tsx
src/svgs/gzmtr/runin/via-station.tsx
src/svgs/gzmtr/station.tsx

#740 Adapt svg-assets@8
